# .----------------.  .----------------.  .-----------------. .----------------.  .----------------.  .----------------.
#| .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. |
#| |     ______   | || |     ____     | || | ____  _____  | || |  _________   | || |     _____    | || |    ______    | |
#| |   .' ___  |  | || |   .'    `.   | || ||_   \|_   _| | || | |_   ___  |  | || |    |_   _|   | || |  .' ___  |   | |
#| |  / .'   \_|  | || |  /  .--.  \  | || |  |   \ | |   | || |   | |_  \_|  | || |      | |     | || | / .'   \_|   | |
#| |  | |         | || |  | |    | |  | || |  | |\ \| |   | || |   |  _|      | || |      | |     | || | | |    ____  | |
#| |  \ `.___.'\  | || |  \  `--'  /  | || | _| |_\   |_  | || |  _| |_       | || |     _| |_    | || | \ `.___]  _| | |
#| |   `._____.'  | || |   `.____.'   | || ||_____|\____| | || | |_____|      | || |    |_____|   | || |  `._____.'   | |
#| |              | || |              | || |              | || |              | || |              | || |              | |
#| '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |
# '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'

#when the duability is less then this amount
WarnAt: 10

Permissions: true

Permission: "plugin.warn.use"

Worlds:
  - "world"
  - "world_nether"

Items:
  - "IRON_PICKAXE"
  - "IRON_AXE"

Enable_Title: true

Title_First: "&4Warning"

Title_Second: "&7Your tool will &cbreak &7soon!"

Enable_Message: false

Message: "&8[&3Server&8] &7Your tool will &cbreak &7soon! &8(<item>&8)"

Enable_Sound: true

Sound:

  Type: "BLOCK_ANVIL_BREAK"

  Volume: 1

  Pitch: 2